### PR TITLE
Reactivated VertexNotePlugIn

### PR DESCRIPTION
**Pull request by ma15569**
Reactivated VertexNotePlugIn

### CODE REVIEW

**Review by mukoki — APPROVED** [review]
Seems that it has been deactivated during migration to github, but I can't remember why.

**Comment by mukoki** [comment]
Peppe, I merged your request so that you can check it.
The VertexNotePlugin is not very intuitive as you are supposed to have defined the attribute you want to show in the VertexPlugIn before using it. Hence, you can edit the visible attribute, but the checkbox of the VertexNotePlugIn is of no use as you can't deactivate attribute display.
Also the pre-condition to run the plugin (layer must have an external symbol and a feature and only one must be selected should be implemented with EnableCheck method to follow the usual way.

**Comment by ma15569** [comment]
Hi Michaël,

*The VertexNotePlugin is not very intuitive as you are supposed to have
defined the attribute you want to show in the VertexPlugIn before using it.
Hence, you can edit the visible attribute, but the checkbox of the
VertexNotePlugIn is of no use as you can't deactivate attribute display.*
"Show label" checkbox on VertexNote Dialog should be deactivated if
VertexParams.textEnabled is off

*Also the pre-condition to run the plugin (layer must have an external
symbol and a feature and only one must be selected should be implemented
with EnableCheck method to follow the usual way.*
There are some warning messages associated with these pre-conditions. An
enableCheck is more preferable, as you mentioned

ASAP I will work on these two enhancements.

Thanks Michael
Peppe

Il giorno mer 19 ott 2022 alle ore 09:12 Michaël Michaud <
***@***.***> ha scritto:

**Comment by mukoki** [comment]
Nothing important for me, just noticed it while testing the merge.

**Comment by edeso** [comment]
> Seems that it has been deactivated during migration to github, but I can't remember why.

just checked and indeed. latest on https://sourceforge.net/p/jump-pilot/code/HEAD/tree/plug-ins/CadPlan_VertexSymbols/trunk/src/plugins/StylerMenuPlugIn.java does not match the initial check-in state https://github.com/ma15569/vertex-symbols/blob/cbaad1c3e470d47e41774f2e5ea5386119a2943b/src/main/java/com/cadplan/vertex_symbols/jump/plugins/StylerMenuPlugIn.java. 

can't say why i disabled it though anymore.

**Pull request merged**
